version: "3.8"
networks:
  baloot:
    external: True
    name: baloot

services:
  db:
    image: mariadb:latest
    restart: always
    deploy:
      placement:
        constraints:
        - node.labels.type == databases
        - node.labels.servernumber == 1
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
    volumes:
      - /mnt/databases:/var/lib/mysql
      - "/mnt/databases_conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro"
    networks:
      baloot:

  web:
    hostname: web
    image: wordpress:latest
    ports:
      - "8080:80"
    deploy:
      placement:
        constraints:
        - node.labels.type == swarm
        - node.labels.servernumber == 1
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

    networks:
      baloot:
    volumes:
      - /mnt/wp:/var/www/html/
