---
# - name: Manage wordpress container
#   hosts: "{{ database_host_group|default('database') }}"
#   gather_facts: false
#   user: root
#   pre_tasks:
#     - name: Ensure database service is running
#       service: name={{ item }} state=started
#       with_items:
#       - mysql 
#     #TODO install database if necessory

- name: Gather host facts
  hosts: "{{ nginx_host_group|default('nginx') }}"
  gather_facts: "{{ nginx_host_group | default(True) }}"
  tags:
    - always

- name: Config nginx for domain with ssl and without
  gather_facts: False
  hosts: "{{ nginx_host_group|default('nginx') }}"
  tasks:
    - name: Manage nginx config file
      import_role:
        name: nginx
  vars_files:
    - "/mnt/{{ user_name|default('example') }}-{{ project_name|default('project') }}-value.yml"     
